# Generated by Django 5.0.1 on 2024-01-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='human',
            name='email',
            field=models.EmailField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='human',
            name='image',
            field=models.ImageField(blank=True, default='def.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='human',
            name='age',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='human',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=6, null=True),
        ),
    ]
