# Generated by Django 5.0.1 on 2024-01-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AA', '0002_human_address_human_email_human_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='address',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
