# Generated by Django 5.0.1 on 2024-01-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AA', '0003_alter_human_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='image',
            field=models.ImageField(default='def.jpg', upload_to='images/'),
        ),
    ]
